/* Automatically generated by './build/bin/build-entry.js' */

import ITableList from './components/table-list/index.js';
import IMenu from './components/menu/index.js';

const components = [
  ITableList,
  IMenu,
];

const install = function(Vue /* , opts = {} */) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.1.0',
  install,
  ITableList,
  IMenu
};

export {
  ITableList,
  IMenu
}
